version: '3.9'

services:
  app:
    container_name: cnt_app
    image: img_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./static:/app/static